name: Localazy Create Pull Request

on: workflow_dispatch

jobs:

  localazy-download-to-pr:
    name: Download strings from Localazy and create PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: localazy/download@v1
        with:
          read_key: ${{ secrets.LOCALAZY_READ_KEY }}
          write_key: ${{ secrets.LOCALAZY_WRITE_KEY }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Sync translations from Localazy"
          commit-message: "[localazy] Automated translation download"
